
import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author carlo
 */
public class FVentana extends javax.swing.JFrame {

    double informacion_dactilar[];
    int num_dedos_ingresados = 0;

    public FVentana() {
        initComponents();
        int num_dedos = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el numero de dedos"));
        informacion_dactilar = new double[num_dedos];
    }

    public void dibujar(Graphics g) {
        int x = 15, x1 = 15;
        int y = 200, y1 = 200;
        boolean valor = false;
        for (int i = 0; i < num_dedos_ingresados; i++) {
                    g.setColor(new Color (153,153,153));
                    g.fillRect(x,y-(int)informacion_dactilar[i],10,(int)informacion_dactilar[i]);
                    if (valor == true){
                        g.setColor(Color.yellow);
                        g.drawLine(x1+10, y1-(int)informacion_dactilar[i-1], x, y-(int)informacion_dactilar[i]);
                        x1+=25;
                   }
                    x+= 25;
                    valor =true;
        }
        int promedio = 0;
        int suma = 0;
        for (int i = 0; i < informacion_dactilar.length; i++) {
            suma = suma + (int) informacion_dactilar[i];
            promedio = suma / (int) informacion_dactilar.length;
        }
        g.drawString("El promedio es: " + promedio, 20, 20);
        
        double var_max = 1;
        for (int i = 0; i < informacion_dactilar.length; i++) {
            if (informacion_dactilar[i] > var_max) {
                var_max = informacion_dactilar[i];
            }
        }
        g.drawString("El valor máximo es: " + var_max, 20, 30);
        
        double var_min = 100;
        for (int i = 0; i < informacion_dactilar.length; i++) {
            if (informacion_dactilar[i] < var_min) {
                var_min = informacion_dactilar[i];
            }
        }
        g.drawString("El valor minimo es: " + var_min, 20, 40);
        
        
    }

    /*public void dibujar(Graphics g){
    g.setColor(Color.yellow);
    g.fillRect(100, 100, 50, 50);
    g.setColor(Color.green);
    g.fillOval(50, 50, 50, 50);
}*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PContenedor = new javax.swing.JPanel(){
            public void paint(Graphics g){
                super.paint(g);
                dibujar(g);
            }
        };
        CTDato = new javax.swing.JTextField();
        BAgregar = new javax.swing.JButton();
        BCalcular = new javax.swing.JButton();
        CBOperacion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PContenedor.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout PContenedorLayout = new javax.swing.GroupLayout(PContenedor);
        PContenedor.setLayout(PContenedorLayout);
        PContenedorLayout.setHorizontalGroup(
            PContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PContenedorLayout.setVerticalGroup(
            PContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );

        CTDato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tamaño Dedo Índice", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Narrow", 0, 24))); // NOI18N

        BAgregar.setText("Agregar");
        BAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BAgregarMouseClicked(evt);
            }
        });

        BCalcular.setText("Calcular");
        BCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCalcularMouseClicked(evt);
            }
        });

        CBOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mínimo", "Máximo", "Promedio", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CTDato, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(BAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(CBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(BCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CTDato, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(153, 153, 153))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BAgregarMouseClicked
        double tam_dedo_capturado
                = Double.parseDouble(CTDato.getText());
        informacion_dactilar[num_dedos_ingresados] = tam_dedo_capturado;
        num_dedos_ingresados++;
        imprimirDatos();
        PContenedor.repaint();
    }//GEN-LAST:event_BAgregarMouseClicked

    private void BCalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCalcularMouseClicked
        int opcion = CBOperacion.getSelectedIndex();
        switch (opcion) {
            case 0:
                minimo();
                break;
            case 1:
                maximo();
                break;
            case 2:
                media();
                break;
        }
    }//GEN-LAST:event_BCalcularMouseClicked
    public void imprimirDatos() {
        CTDato.setText("");
        for (int i = 0; i < num_dedos_ingresados; i++) {
            System.out.println(informacion_dactilar[i] + "\n");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAgregar;
    private javax.swing.JButton BCalcular;
    private javax.swing.JComboBox<String> CBOperacion;
    private javax.swing.JTextField CTDato;
    private javax.swing.JPanel PContenedor;
    // End of variables declaration//GEN-END:variables

    private void minimo() {
        double var_minimo = 10000;
        for (int x = 0; x < num_dedos_ingresados; x++) {
            if (informacion_dactilar[x] < var_minimo) {
                var_minimo = informacion_dactilar[x];
            }

        }
         letrero("El valor minimo es: "+var_minimo);
         
    }
    private void maximo(){
        double max = informacion_dactilar[0];
        for(int x=0; x<num_dedos_ingresados;x++){
            if(informacion_dactilar[x]>max){
                max=informacion_dactilar[x];
            }
        }
        letrero("El valor máximo es: "+max);
    }
    private void media(){
        double m=0;
        for(int x=0; x<num_dedos_ingresados;x++){
            m = m+informacion_dactilar[x];
        }
        double media;
        media = m/num_dedos_ingresados;
        letrero("El promedio es: "+media);
        
    }
    public static void letrero(String letrero){
        JOptionPane.showMessageDialog(null, letrero);
    }
    
}
