
import java.awt.Graphics;
import javax.swing.JOptionPane;



public class PUniverso extends javax.swing.JPanel {

    Torre  torres[];
    public PUniverso() {
        initComponents();
        torres = new Torre[3];
        torres[0]= new Torre(5,200,100);
        torres[1]= new Torre(5,400,100);
        torres[2]= new Torre(5,600,100);
        torres[0].insertar(new Disco(0,0,10));
        torres[0].insertar(new Disco(0,0,8));
        torres[0].insertar(new Disco(0,0,6));
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g); 
        for (int i = 0; i < torres.length; i++) {
            torres[i].dibujarTorre(g);
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    void moverDisco(int desde, int hasta) {
        Disco validacion = torres[desde-1].Pop2();
        if (validacion != null) {
            if (torres[hasta-1].validar(validacion)) {
                Disco discoFuera = torres[desde-1].pop();
                torres[hasta-1].insertar(discoFuera);
                repaint();
            } else {
                JOptionPane.showMessageDialog(null, "El disco es más grande.", "Movimiento inválido", 2);
            }
        }
       
        
        
        
        
        /*torres[hasta-1].insertar(torres[desde-1].pop());
        repaint();*/
        
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
