
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author carlo
 */
public class PElemento extends javax.swing.JPanel {

    /**
     * Creates new form PElemento
     */
    public PElemento(String producto, String nombre, Icon imagen ) {
        initComponents();
        CTProducto.setText(producto);
        CTNombre.setText(nombre);
        LImagen.setIcon(imagen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LImagen = new javax.swing.JLabel();
        CTProducto = new javax.swing.JTextField();
        BCargar = new javax.swing.JButton();
        CTNombre = new javax.swing.JTextField();

        BCargar.setText("Cargar");
        BCargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCargarMouseClicked(evt);
            }
        });

        CTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CTProducto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LImagen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BCargar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(LImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CTProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BCargar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BCargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCargarMouseClicked
        JFileChooser selector  = new JFileChooser();// muestra una ventana para seleccionar un archivo
        int n = selector.showOpenDialog(this);//muestra el dialogo d apertura
        if(n == JFileChooser.APPROVE_OPTION){
            System.out.println("ruta: "+selector.getSelectedFile().getPath());
            ImageIcon img = new ImageIcon(selector.getSelectedFile().getPath());
            LImagen.setIcon(img);
        }
        
    }//GEN-LAST:event_BCargarMouseClicked

    private void CTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTNombreActionPerformed

    public JTextField getCTNombre() {
        return CTNombre;
    }

    public void setCTNombre(JTextField CTNombre) {
        this.CTNombre = CTNombre;
    }

    public JTextField getCTProducto() {
        return CTProducto;
    }

    public void setCTProducto(JTextField CTProducto) {
        this.CTProducto = CTProducto;
    }

    public JLabel getLImagen() {
        return LImagen;
    }

    public void setLImagen(JLabel LImagen) {
        this.LImagen = LImagen;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCargar;
    private javax.swing.JTextField CTNombre;
    private javax.swing.JTextField CTProducto;
    private javax.swing.JLabel LImagen;
    // End of variables declaration//GEN-END:variables
}
